version: "3.9"

services:

  db:
    image: postgres:latest
    container_name: store-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=app_store
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data: