version: "3.9"

services:

  db:
    image: postgres:latest
    container_name: store-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=app_store
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  pgadmin:
    container_name: store-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: '1234'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mongo:
    image: mongo:latest
    container_name: inventory-mongo
    environment:
      MONGO_INITDB_DATABASE: inventory
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: inventory-mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    links:
      - mongo





volumes:
  postgres-data:
  pgadmin-data:
  mongo-data:
  mongo-express-data: