MINIO_STORAGE_ENDPOINT = "minionovapardaz.darkube.app"
MINIO_STORAGE_ACCESS_KEY = 'mwtRxaxYidNTrsUtmrWtYaO0tyJPIOmE'
MINIO_STORAGE_SECRET_KEY = "jPouArcmFgziXUciHxcS583J6K50HdiS"
MINIO_STORAGE_USE_HTTPS = True
MINIO_STORAGE_MEDIA_BUCKET_NAME = "store-media"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_MEDIA_USE_PRESIGNED = True
