"""Adding Logo into Store model

Revision ID: a0b333551feb
Revises: 7c6030dd327b
Create Date: 2024-05-16 12:40:31.192537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b333551feb'
down_revision: Union[str, None] = '7c6030dd327b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('logo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'logo')
    # ### end Alembic commands ###
