"""add autoincrement into store table for id

Revision ID: fe0cf17bfe12
Revises: e4adc04dc949
Create Date: 2024-04-28 23:54:03.023750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0cf17bfe12'
down_revision: Union[str, None] = 'e4adc04dc949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
